apiVersion: v2
name: infra-helm
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

dependencies:
- name: prometheus
  version: 18.0
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-elasticsearch-exporter
  version: 5.0.0
  repository: https://prometheus-community.github.io/helm-charts
- name: elasticsearch
  version: 7.9.3
  repository: https://helm.elastic.co
- name: kibana
  version: 7.9.3
  repository: https://helm.elastic.co
- name: fluentd-elasticsearch
  version: 11.0.1
  repository: https://kokuwaio.github.io/helm-charts
- name: prometheus-elasticsearch-exporter
  version: 4.7.0
  repository: https://prometheus-community.github.io/helm-charts
- name: grafana
  version: 6.0.0
  repository: https://grafana.github.io/helm-charts
- name: kafka
  version: 0.21.2
  repository: https://charts.helm.sh/incubator  

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
sources:
  - https://github.com/cyse7125-fall2022-group03/helm-infra.git
maintainers:
  - name: Ketki Kule
    email: kule.k@northeastern.edu
  - name: Sandeep Bharat Wagh
    email: wagh.sn@northeastern.edu
  - name: Vignesh Gunasekaran
    email: gunasekaran.v@northeastern.edu