apiVersion: v1
kind: Secret
metadata:
  name: example-com-r53-creds
  namespace: cert-manager
type: Opaque
data:
  secret-access-key: QzdDeFhxSUFGMGpVRVV2SkVVa21aVVp5Tm9lRnB1NS8yWk50enVZSQ==
  #base64 secretaccesskey