apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo
  namespace: istio-system
spec:
  commonName: ketkikule.me
  dnsNames:
  - ketkikule.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: letsencrypt-stage