apiVersion: v1
kind: Secret
metadata:
  name: example-com-r53-creds
  namespace: cert-manager
type: Opaque
data:
  secret-access-key: {{ .Values.certificate.secretAccessKey }}
  #base64 secretaccesskey