apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp
  namespace: istio-system
spec:
  commonName: sandeepwagh.me
  dnsNames:
  - sandeepwagh.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: letsencrypt-stage