apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp
  namespace: istio-system
spec:
  commonName: {{ .Values.certificate.domainName }}
  dnsNames:
  - {{ .Values.certificate.domainName }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: letsencrypt-stage